# Generated by Django 4.1.5 on 2023-01-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('user_id', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
