# Generated by Django 4.1.5 on 2023-01-29 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 16, 34, 6, 578198)),
        ),
    ]
